[background]
path = "/usr/share/hyperbola/wallpapers/main-login.png"
fit = "Fill"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "Bibata-Modern-Classic"
theme_name = "adw-gtk3-dark"

[appearance]
greeting_msg = "Welcome to Hyperbola"
