--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/ml4w-hyprland/wallpapers/default.jpg"

-- Special
background="#071115"
foreground="#bfad99"
cursor="#bfad99"

-- Colors
color0="#071115"
color1="#273D42"
color2="#344A4D"
color3="#44595A"
color4="#4C5F5F"
color5="#546868"
color6="#637876"
color7="#bfad99"
color8="#85796b"
color9="#273D42"
color10="#344A4D"
color11="#44595A"
color12="#4C5F5F"
color13="#546868"
color14="#637876"
color15="#bfad99"
