# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/ml4w-hyprland/wallpapers/default.jpg'

# Special
background='#071115'
foreground='#bfad99'
cursor='#bfad99'

# Colors
color0='#071115'
color1='#273D42'
color2='#344A4D'
color3='#44595A'
color4='#4C5F5F'
color5='#546868'
color6='#637876'
color7='#bfad99'
color8='#85796b'
color9='#273D42'
color10='#344A4D'
color11='#44595A'
color12='#4C5F5F'
color13='#546868'
color14='#637876'
color15='#bfad99'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
